module(name = "platformio_rules")

bazel_dep(name = "rules_cc", version = "0.2.8")
bazel_dep(name = "rules_python", version = "1.6.3")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "stardoc", version = "0.8.0", repo_name = "io_bazel_stardoc")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(python_version = "3.12")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "py_deps",
    python_version = "3.12",
    requirements_lock = "//:requirements_lock.txt",
)
use_repo(pip, "py_deps")

########################### Load Archives ###########################
http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Google testing and mocking framework for C++.
bazel_dep(name = "googletest", version = "1.17.0.bcr.1")

# Stardoc, documentation generator for custom Bazel rules.
http_archive(
    name = "io_bazel_rules_sass",
    sha256 = "05db38271919d3d209a9f58db412a5bf2af2def7d4c1fae17b401dccbad97178",
    strip_prefix = "rules_sass-1.57.0",
    url = "https://github.com/bazelbuild/rules_sass/archive/1.57.0.zip",
)
bazel_dep(name = "bazel_skylib", version = "1.8.2")

############### Load backwards compatible dependencies ###############
# Most of these are not actually necessary, but we should load them to keep deps somewhat consistent
p = use_extension("//bazel:deps.bzl", "platformio_rules_dependencies")

pt = use_extension("//bazel:transitive.bzl", "platformio_rules_transitive_dependencies")

ptt = use_extension("//bazel:pip_parse.bzl", "platformio_rules_pip_parse_dependencies")

pttt = use_extension("//bazel:pip_install.bzl", "platformio_rules_pip_install_dependencies")
