# buildifier: disable=module-docstring
module(name = "platformio_rules")

# https://github.com/bazelbuild/rules_cc
bazel_dep(name = "rules_cc", version = "0.2.17")

# https://github.com/bazel-contrib/rules_python
bazel_dep(name = "rules_python", version = "1.9.0-rc1")

# https://github.com/bazelbuild/platforms
bazel_dep(name = "platforms", version = "1.0.0")

# https://github.com/bazelbuild/stardoc
bazel_dep(name = "stardoc", version = "0.8.1", repo_name = "io_bazel_stardoc")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(python_version = "3.14")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
# Available versions are listed in @rules_python//python:versions.bzl

pip.parse(
    hub_name = "py_deps",
    python_version = "3.14",
    requirements_lock = "//:requirements_lock.txt",
    requirements_windows = "//:requirements_windows.txt",
)
use_repo(pip, "py_deps")

########################### Load Archives ###########################
http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Google testing and mocking framework for C++.
# https://github.com/google/googletest
bazel_dep(name = "googletest", version = "1.17.0.bcr.2")

# https://github.com/bazelbuild/bazel-skylib
bazel_dep(name = "bazel_skylib", version = "1.9.0")

# Hedron's Compile Commands Extractor for Bazel
# https://github.com/hedronvision/bazel-compile-commands-extractor
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    commit = "7fe1eab26d2b8eeb5e1c6a2f38bddb001e3f9696",
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
)
# bazel run @hedron_compile_commands//:refresh_all
